
services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  car-service:
    build: ./car-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  booking-service:
    build: ./booking-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - user-service
      - car-service

volumes:
  mongodb_data: