name: Node.js Microservices CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, car-service, booking-service] # Folder names of each service if they are in subfolders

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Optional: If you have tests
      - name: Run tests
        run: npm test || echo "No tests yet"

  
